### ISSUE TITLE
This is a device which is not listed in this library.

### ISSUE THREAD

**Issue by xxxpo** [InderKumarRathore/DeviceGuru#119]
Your device hardware string is|iPad14,3|  iPad Pro(11-inch)(4th) 1TB
Your device hardware string is|iPad14,4|  iPad Pro(11-inch)(4th) 16GB
Your device hardware string is|iPad14,5|  iPad Pro(12.9-inch)(6th) 1TB|16GB

On the simulators.

**Comment by InderKumarRathore** [comment]
Could you please add these devices and raise a PR

**Comment by cheizer** [comment]
I'm also getting it for ---

Your device hardware string is|iPad14,6|"

**Comment by InderKumarRathore** [comment]
Similar ids were added https://github.com/InderKumarRathore/DeviceGuru/pull/108
`iPad14,3-A` / `iPad14,3-B` not sure why it's prefixed with A & B
Can you test on actual device and see what is coming? If we need to support these keys then code needs to be changed.
Since currently key to value is one to one mapping but it looks like with this (simulator one)
there is two keys with one value

**Comment by cliffjoyce** [comment]
Your device hardware string is|iPad16,5|" which is an iPad Pro M4 WiFi only.
