### ISSUE TITLE
Missing example project

### ISSUE THREAD

**Issue by lfarah** [InderKumarRathore/DeviceGuru#13]
Normally, this type of projects would have an example app, as you can see [here](https://github.com/MatthewYork/DateTools) and [here](https://github.com/diy/nsstringemojize).
I'll create an example and push a PR. 

What do you think? :smiley:

**Comment by InderKumarRathore** [comment]
@lfarah I don't think a project is required for this since there is nothing complex that can be explained using a sample project. It's just a line of code. However we can create a project which can cover all the features of the library. Let me give some time to think on it. Also I have to refactor it again and then I can add a sample as well.

**Comment by lfarah** [comment]
Hey, I get your point: it's just a couple lines of code. The thing is: _As a developer, I'm really lazy_. When testing a library, I just open the Example Project and run to see what happens. To test _Device Guru_ today, the dev has to download _DeviceGuru_, create a new project and then run.
In the end of the day, **it's all about lowering the experimentation and learning curves**
What are your thoughts?

**Comment by lfarah** [comment]
And about refactoring the code, add issues and I can help you on that! :smile:

**Comment by InderKumarRathore** [comment]
Hmmmm that a problem, anyway having project seems good option now. I'm adding tasks which need to be done, if you can help me that would be cool

**Comment by InderKumarRathore** [comment]
#18
