### ISSUE TITLE
iPhone10,6 not listed

### ISSUE THREAD

**Issue by Francescu** [InderKumarRathore/DeviceGuru#51]
I get this console message:

> Your device hardware string is: %@ iPhone10,6
> This is a device which is not listed in this category. Please visit https://github.com/InderKumarRathore/DeviceGuru and add a comment there.

Although I'm using 4.0.4 and I clearly see `10,6` in the list.

<img width="635" alt="capture d ecran 2018-07-17 a 11 20 33" src="https://user-images.githubusercontent.com/1433362/42808419-93ccd660-89b3-11e8-9f22-55c9b2132d70.png">

**Comment by InderKumarRathore** [comment]
Hi Francescu,
Seems weird to me, can you please debug and check why this is not returning iphoneX?
You can use TestDeviceGuru workspace to test this repo. Also I've updated the logging, I doubt that your **iPhone10,6** has a space initially that's why it's not returning correct value. Please check if there is a space in your hardware string like 

`
"iPhone10,6" == " iPhone10,6" // is always false.
`

If this is the case then I might not be able to fix it since I don't have iPhone X, would be better if you share some more info. A workaround would be to trim hardware string.

**Comment by Francescu** [comment]
I think it's not linked to the device itself, I just got for an iPhone 6s

```
This is a device which is not listed in this category. Please visit https://github.com/InderKumarRathore/DeviceGuru and add a comment there.
Your device hardware string is: %@ iPhone8,1
```

It's strange

**Comment by InderKumarRathore** [comment]
Can you please confirm if the space is coming in the device string?
Also confirm the iOS versions on both the devices.
